<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once __DIR__ . '/../../helpers/auth.php';
require_role(['doctor', 'nutritionist', 'admin']);
require_once __DIR__ . '/../../../DB.php';

// Load env from Admin/env (project-relative)
$env_content = @file_get_contents(__DIR__ . '/../../../Admin/env');
if ($env_content !== false) {
    $lines = explode("\n", $env_content);
    foreach ($lines as $line) {
        if (strpos($line, '=') !== false) {
            list($key, $value) = explode('=', $line, 2);
            putenv(trim($key) . '=' . trim($value));
            $_ENV[trim($key)] = trim($value);
        }
    }
}

require_once __DIR__ . '/../../../Mealplan.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

$data = json_decode(file_get_contents('php://input'), true);
$member_id = $data['member_id'] ?? null;

if (!$member_id) {
    http_response_code(400);
    echo json_encode(['error' => 'Member ID required']);
    exit;
}

// Fetch user data
$user_query = "SELECT u.First_Name, u.Last_Name, u.Email, u.DOB, u.Gender, m.Body_fat, m.Height, m.Weight, m.BMI, m.Experience_Level, m.Training_Goals, m.Injuries, m.Medical_Condition FROM UserProfile u JOIN MemberProfile m ON u.User_ID = m.Member_Id WHERE u.User_ID = ?";
$stmt = $conn->prepare($user_query);
if (!$stmt) {
    http_response_code(500);
    echo json_encode(['error' => 'Database prepare failed']);
    exit;
}
$stmt->bind_param('i', $member_id);
$stmt->execute();
$user = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$user) {
    http_response_code(404);
    echo json_encode(['error' => 'Member not found']);
    exit;
}

// Prepare prompt
$days = 7; // Fixed to 7 days
$goal = "eat healthy based on goals: {$user['Training_Goals']}, considering medical: {$user['Medical_Condition']}, injuries: {$user['Injuries']}";
$prompt = "You are a helpful nutritionist. Provide a {$days}-day meal plan for a user who wants to {$goal}. User details: Age " . (date('Y') - date('Y', strtotime($user['DOB']))) . ", Gender {$user['Gender']}, Height {$user['Height']}cm, Weight {$user['Weight']}kg, BMI {$user['BMI']}, Body Fat {$user['Body_fat']}%, Experience {$user['Experience_Level']}. Respond only with a valid JSON object in the following format: {\"program\": {\"title\": \"{$days}-Day Meal Plan\", \"description\": \"Balanced meal plan generated by AI for {$goal}\", \"totalCalories\": 2000, \"carbs\": 250, \"protein\": 150, \"fats\": 70, \"days\": {$days}}, \"days\": {\"day1\": [{\"meal\": \"breakfast\", \"name\": \"Oatmeal with Fruits\", \"description\": \"A nutritious start to the day...\", \"calories\": 300, \"ingredients\": [\"oats\", \"banana\", \"milk\"], \"instructions\": \"Cook oats and add toppings.\"}, {\"meal\": \"lunch\", ...}, {\"meal\": \"dinner\", ...}], \"day2\": [...], ... up to day{$days}}}. Include 3 meals per day (breakfast, lunch, dinner). Vary meals to ensure balanced nutrition. Ensure all meal and program details are provided in the response.";

// Call Gemini API
$response = callGemini($prompt, 'gemini-1.5-flash', true);

if (!is_array($response)) {
    http_response_code(500);
    echo json_encode(['error' => 'Failed to generate plan: ' . $response]);
    exit;
}

// Parse the JSON response
$program = $response['program'] ?? [];
$days_data = $response['days'] ?? [];

// Insert into MealPlan
$programData = [
    'Title' => $program['title'] ?? "{$days}-Day Meal Plan",
    'Description' => $program['description'] ?? 'Balanced meal plan generated by AI',
    'Total_daily_Calories' => $program['totalCalories'] ?? 2000,
    'Carbs_grams_per_day' => $program['carbs'] ?? 250,
    'Protein_grams_per_day' => $program['protein'] ?? 150,
    'Fats_grams_per_day' => $program['fats'] ?? 70,
    'Status' => 'Active',
    'Start_Date' => date('Y-m-d'),
    'End_Date' => date('Y-m-d', strtotime('+' . $days . ' days')),
    'Created_at' => date('Y-m-d H:i:s'),
    'Updated_at' => date('Y-m-d H:i:s'),
    'Nutritionist_ID' => $_SESSION['user_id'],
    'Member_Id' => $member_id
];
$mealPlanId = insert('MealPlan', $programData);

if (!$mealPlanId) {
    http_response_code(500);
    echo json_encode(['error' => 'Failed to insert meal plan']);
    exit;
}

$mealSequence = 0;
// Insert meals
foreach ($days_data as $day => $meals) {
    foreach ($meals as $meal) {
        $mealType = $meal['meal'] ?? 'Breakfast';
        $name = $meal['name'] ?? 'Unknown Meal';
        $description = $meal['description'] ?? '';
        $calories = $meal['calories'] ?? 0;
        $ingredients = $meal['ingredients'] ?? [];
        $instructions = $meal['instructions'] ?? '';
        
        // Determine Target_Time_of_Day
        $timeOfDay = 1; // Default breakfast
        if (strtolower($mealType) === 'lunch') $timeOfDay = 2;
        elseif (strtolower($mealType) === 'dinner') $timeOfDay = 3;
        
        // Insert into Meal
        $mealData = [
            'Name' => $name,
            'Sequence_Order' => $mealSequence++,
            'Target_Time_of_Day' => $timeOfDay,
            'Created_at' => date('Y-m-d H:i:s'),
            'Updated_at' => date('Y-m-d H:i:s'),
            'Meal_Plan_ID' => $mealPlanId
        ];
        $mealId = insert('Meal', $mealData);
        
        if ($mealId && is_array($ingredients)) {
            foreach ($ingredients as $ingredient) {
                // Check if FoodItem exists
                $existingFood = select('FoodItem', 'Food_Item_ID', ['Name' => $ingredient]);
                if (empty($existingFood)) {
                    // Insert new FoodItem with dummy values
                    $foodData = [
                        'Name' => $ingredient,
                        'Brand' => 0, // Dummy brand ID
                        'Serving_Size' => 100, // grams
                        'Calories' => 50, // dummy
                        'Sugar_Grams' => 5,
                        'Fats_Grams' => 2,
                        'Fiber_Grams' => 2,
                        'Protein_Grams' => 5,
                        'Carbs_Grams' => 10,
                        'Created_at' => date('Y-m-d H:i:s'),
                        'Updated_at' => date('Y-m-d H:i:s')
                    ];
                    $foodId = insert('FoodItem', $foodData);
                } else {
                    $foodId = $existingFood[0]['Food_Item_ID'];
                }
                
                // Insert into MealPlanItem
                $itemData = [
                    'Quantity_Servings' => 1,
                    'Notes' => '',
                    'Created_at' => date('Y-m-d H:i:s'),
                    'Updated_at' => date('Y-m-d H:i:s'),
                    'Meal_ID' => $mealId,
                    'Food_Item_ID' => $foodId
                ];
                insert('MealPlanItem', $itemData);
            }
        }
    }
}

echo json_encode(['success' => true, 'plan_id' => $mealPlanId]);
?>
