<?php
// Load environment variables from .env file
function loadEnv($path = '.env') {
    if (!file_exists($path)) {
        die("Error: .env file not found. Please create a .env file with your GEMINI_API_KEY.\n");
    }
    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        if (strpos(trim($line), '#') === 0) continue; // Skip comments
        list($name, $value) = explode('=', $line, 2);
        $name = trim($name);
        $value = trim($value);
        putenv("$name=$value");
        $_ENV[$name] = $value;
    }
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meal Plan Generator</title>
    <link rel="stylesheet" href="Home.css">
</head>
<body>
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh; flex-direction: column;">
        <h1>Generate Your Meal Plan</h1>
        <form method="post">
            <label for="goal">Goal:</label>
            <input type="text" id="goal" name="goal" value="eat healthy and maintain weight" required><br><br>
            <label for="days">Number of Days:</label>
            <input type="number" id="days" name="days" value="7" min="1" max="30" required><br><br>
            <button class="super-button" type="submit">
                <span>Generate Meal Plan</span>
            </button>
        </form>
    </div>
</body>
</html>
<?php
exit;
}

// Load the .env file only when processing POST
loadEnv();

// Function to call Gemini API
function callGemini($prompt, $model = 'gemini-2.5-flash', $jsonResponse = false) {
    $apiKey = getenv('GEMINI_API_KEY');
    if (!$apiKey) {
        die("Error: GEMINI_API_KEY not set in .env file.\n");
    }

    $url = "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key={$apiKey}";

    $data = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $prompt]
                ]
            ]
        ]
    ];

    if ($jsonResponse) {
        $data['generationConfig'] = [
            'responseMimeType' => 'application/json'
        ];
    }

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Content-Type: application/json'
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($httpCode !== 200) {
        return "Error: API request failed with status {$httpCode}. Response: {$response}";
    }

    $result = json_decode($response, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        return "Error: Invalid JSON response from API.";
    }

    $text = $result['candidates'][0]['content']['parts'][0]['text'] ?? 'Error: No response text found.';

    if ($jsonResponse) {
        // Parse the JSON response
        $parsed = json_decode($text, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            return "Error: Invalid JSON from LLM.";
        }
        return $parsed;
    }

    return $text;
}

// Get form inputs
$goal = $_POST['goal'] ?? 'eat healthy and maintain weight';
$days = (int)($_POST['days'] ?? 7);

// $history = retrieve history
// Example usage
$prompt = "You are a helpful nutritionist. Provide a {$days}-day meal plan for a user who wants to {$goal}. Respond only with a valid JSON object in the following format: {\"program\": {\"title\": \"{$days}-Day Meal Plan\", \"description\": \"Balanced meal plan generated by AI for {$goal}\", \"totalCalories\": 2000, \"carbs\": 250, \"protein\": 150, \"fats\": 70, \"days\": {$days}}, \"days\": {\"day1\": [{\"meal\": \"breakfast\", \"name\": \"Oatmeal with Fruits\", \"description\": \"A nutritious start to the day...\", \"calories\": 300, \"ingredients\": [\"oats\", \"banana\", \"milk\"], \"instructions\": \"Cook oats and add toppings.\"}, {\"meal\": \"lunch\", ...}, {\"meal\": \"dinner\", ...}], \"day2\": [...], ... up to day{$days}}}. Include 3 meals per day (breakfast, lunch, dinner). Vary meals to ensure balanced nutrition. Ensure all meal and program details are provided in the response.";

$response = callGemini($prompt, 'gemini-2.5-flash', true); // true for JSON response

echo '<!DOCTYPE html><html><head><link rel="stylesheet" href="Home.css"></head><body><div style="padding: 20px;">';

if (is_array($response)) {
    // Parse the JSON response to variables
    require_once 'DB.php'; // Include the DB functions
    
    // Get Member_Id for Ahmed (adjust as needed)
    $user = select('UserProfile', 'User_ID', ['First_Name' => 'Pablo']);
    if (empty($user)) {
        die("User not found.");
    }
    $userId = $user[0]['User_ID'];
    
    $member = select('MemberProfile', 'Member_Id', ['Member_Id' => $userId]);
    if (empty($member)) {
        die("Member not found.");
    }
    $memberId = $member[0]['Member_Id'];
    
    $program = $response['program'] ?? [];
    $days = $response['days'] ?? $response; // Fallback
    
    // Insert into MealPlan
    $programData = [
        'Title' => $program['title'] ?? '7-Day Meal Plan',
        'Description' => $program['description'] ?? 'Balanced meal plan generated by AI',
        'Total_daily_Calories' => $program['totalCalories'] ?? 2000,
        'Carbs_grams_per_day' => $program['carbs'] ?? 250,
        'Protein_grams_per_day' => $program['protein'] ?? 150,
        'Fats_grams_per_day' => $program['fats'] ?? 70,
        'Status' => 'Active',
        'Start_Date' => date('Y-m-d'),
        'End_Date' => date('Y-m-d', strtotime('+' . ($program['days'] ?? 7) . ' days')),
        'Created_at' => date('Y-m-d H:i:s'),
        'Updated_at' => date('Y-m-d H:i:s'),
        'Nutritionist_ID' => 4,
        'Member_Id' => $memberId
    ];
    $mealPlanId = insert('MealPlan', $programData);
    
    if ($mealPlanId) {
        $mealSequence = 0;
        // Insert meals
        foreach ($days as $day => $meals) {
            $dayNumber = str_replace('day', '', $day);
            foreach ($meals as $meal) {
                $mealType = $meal['meal'] ?? 'Breakfast';
                $name = $meal['name'] ?? 'Unknown Meal';
                $description = $meal['description'] ?? '';
                $calories = $meal['calories'] ?? 0;
                $ingredients = $meal['ingredients'] ?? [];
                $instructions = $meal['instructions'] ?? '';
                
                // Determine Target_Time_of_Day
                $timeOfDay = 1; // Default breakfast
                if (strtolower($mealType) === 'lunch') $timeOfDay = 2;
                elseif (strtolower($mealType) === 'dinner') $timeOfDay = 3;
                
                // Insert into Meal
                $mealData = [
                    'Name' => $name,
                    'Sequence_Order' => $mealSequence++,
                    'Target_Time_of_Day' => $timeOfDay,
                    'Created_at' => date('Y-m-d H:i:s'),
                    'Updated_at' => date('Y-m-d H:i:s'),
                    'Meal_Plan_ID' => $mealPlanId
                ];
                $mealId = insert('Meal', $mealData);
                
                // Insert ingredients into FoodItem and MealPlanItem
                if (is_array($ingredients)) {
                    foreach ($ingredients as $ingredient) {
                        // Check if FoodItem exists
                        $existingFood = select('FoodItem', 'Food_Item_ID', ['Name' => $ingredient]);
                        if (empty($existingFood)) {
                            // Insert new FoodItem with dummy values
                            $foodData = [
                                'Name' => $ingredient,
                                'Brand' => 0, // Dummy brand ID
                                'Serving_Size' => 100, // grams
                                'Calories' => 50, // dummy
                                'Sugar_Grams' => 5,
                                'Fats_Grams' => 2,
                                'Fiber_Grams' => 2,
                                'Protein_Grams' => 5,
                                'Carbs_Grams' => 10,
                                'Created_at' => date('Y-m-d H:i:s'),
                                'Updated_at' => date('Y-m-d H:i:s')
                            ];
                            $foodId = insert('FoodItem', $foodData);
                        } else {
                            $foodId = $existingFood[0]['Food_Item_ID'];
                        }
                        
                        // Insert into MealPlanItem
                        $itemData = [
                            'Quantity_Servings' => 1,
                            'Notes' => '',
                            'Created_at' => date('Y-m-d H:i:s'),
                            'Updated_at' => date('Y-m-d H:i:s'),
                            'Meal_ID' => $mealId,
                            'Food_Item_ID' => $foodId
                        ];
                        insert('MealPlanItem', $itemData);
                    }
                }
            }
        }
        echo "<h1>Meal plan saved to database.</h1>";
        
        // Display the generated plan
        $title = $program['title'] ?? '7-Day Meal Plan';
        $description = $program['description'] ?? 'Balanced meal plan generated by AI';
        $totalCalories = $program['totalCalories'] ?? 2000;
        echo "<h2>$title</h2>";
        echo "<p>$description</p>";
        echo "<p>Total Calories: $totalCalories</p>";
        
        foreach ($days as $day => $meals) {
            $dayName = ucfirst($day);
            echo "<h3>$dayName</h3>";
            foreach ($meals as $meal) {
                $mealType = $meal['meal'] ?? 'Breakfast';
                $name = $meal['name'] ?? 'Unknown Meal';
                $calories = $meal['calories'] ?? 0;
                echo "<p><strong>$mealType:</strong> $name ($calories cal)</p>";
            }
        }
    } else {
        echo "<h1>Failed to create meal plan.</h1>";
    }
} else {
    echo "<h1>$response</h1>";
}
echo '</div></body></html>';
?>