<?php
// Load environment variables from .env file
function loadEnv($path = '.env') {
    if (!file_exists($path)) {
        die("Error: .env file not found. Please create a .env file with your GEMINI_API_KEY.\n");
    }
    $lines = file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        if (strpos(trim($line), '#') === 0) continue; // Skip comments
        list($name, $value) = explode('=', $line, 2);
        $name = trim($name);
        $value = trim($value);
        putenv("$name=$value");
        $_ENV[$name] = $value;
    }
}

// Load the .env file
loadEnv();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatbot - Generate Workout</title>
    <link rel="stylesheet" href="Home.css">
</head>
<body>
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh; flex-direction: column;">
        <h1>Generate Your Workout Plan</h1>
        <form method="post">
            <button class="super-button" type="submit">
                <span>Generate Workout</span>
            </button>
        </form>
    </div>
</body>
</html>
<?php
exit;
}

// Function to call Gemini API
function callGemini($prompt, $model = 'gemini-2.5-flash', $jsonResponse = false) {
    $apiKey = getenv('GEMINI_API_KEY');
    if (!$apiKey) {
        die("Error: GEMINI_API_KEY not set in .env file.\n");
    }

    $url = "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key={$apiKey}";

    $data = [
        'contents' => [
            [
                'parts' => [
                    ['text' => $prompt]
                ]
            ]
        ]
    ];

    if ($jsonResponse) {
        $data['generationConfig'] = [
            'responseMimeType' => 'application/json'
        ];
    }

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        'Content-Type: application/json'
    ]);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($httpCode !== 200) {
        return "Error: API request failed with status {$httpCode}. Response: {$response}";
    }

    $result = json_decode($response, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        return "Error: Invalid JSON response from API.";
    }

    $text = $result['candidates'][0]['content']['parts'][0]['text'] ?? 'Error: No response text found.';

    if ($jsonResponse) {
        // Parse the JSON response
        $parsed = json_decode($text, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            return "Error: Invalid JSON from LLM.";
        }
        return $parsed;
    }

    return $text;
}


// $history = retreive history of ahmed
// Example usage
$prompt = "You are a helpful fitness coach. Provide a 1-week workout plan for a beginner named Ahmed who wants to build muscle. Respond only with a valid JSON object in the following format: {\"program\": {\"title\": \"1-Week Muscle Building Plan\", \"description\": \"Beginner workout plan generated by AI\", \"goal\": \"Build Muscle\", \"weeks\": 1}, \"days\": {\"day1\": [{\"name\": \"Push-ups\", \"description\": \"A bodyweight exercise...\", \"sets\": 3, \"reps\": 10, \"rest\": \"60 seconds\", \"difficulty\": \"Beginner\", \"targetMuscleGroup\": \"Chest\", \"secondaryMuscles\": \"Triceps, Shoulders\", \"instructions\": \"Detailed instructions here...\", \"equipment\": \"Bodyweight\", \"notes\": \"\"}], \"day2\": [...], ... up to day7}}. Include rest days as empty arrays. Vary exercises to target different muscle groups. Ensure all details are provided in the response.";

$response = callGemini($prompt, 'gemini-2.5-flash', true); // true for JSON response

echo '<!DOCTYPE html><html><head><link rel="stylesheet" href="Home.css"></head><body><div style="padding: 20px;">';

if (is_array($response)) {
    // Parse the JSON response to variables
    require_once 'DB.php'; // Include the DB functions
    
    // Get Member_Id for Ahmed
    $user = select('UserProfile', 'User_ID', ['First_Name' => 'Pablo']);
    if (empty($user)) {
        die("User Ahmed not found in UserProfile.");
    }
    $userId = $user[0]['User_ID'];
    
    $member = select('MemberProfile', 'Member_Id', ['Member_Id' => $userId]);
    if (empty($member)) {
        die("Ahmed is not registered as a member.");
    }
    $memberId = $member[0]['Member_Id'];
    
    // Assume Coach_ID is 1 (adjust or query as needed)
    $coachId = 3;
    
    $program = $response['program'] ?? [];
    $days = $response['days'] ?? $response; // Fallback if old format
    
    // Insert into WorkoutProgram
    $programData = [
        'Title' => $program['title'] ?? '1-Week Muscle Building Plan',
        'Description' => $program['description'] ?? 'Beginner workout plan generated by AI',
        'Goal' => $program['goal'] ?? 'Build Muscle',
        'Weeks_Duration' => $program['weeks'] ?? 1,
        'Start_Date' => date('Y-m-d'),
        'End_Date' => date('Y-m-d', strtotime('+' . ($program['weeks'] ?? 1) * 7 . ' days')),
        'Status' => 'Active',
        'Created_at' => date('Y-m-d H:i:s'),
        'Updated_at' => date('Y-m-d H:i:s'),
        'Member_Id' => $memberId,
        'Coach_ID' => $coachId
    ];
    $workoutId = insert('WorkoutProgram', $programData);
    
    if ($workoutId) {
        // Now insert exercises and workout exercises
        $sequence = 1;
        foreach ($days as $day => $exercises) {
            $dayNumber = str_replace('day', '', $day); // e.g., 1,2,3
            foreach ($exercises as $ex) {
                $name = $ex['name'] ?? 'Unknown Exercise';
                $description = $ex['description'] ?? '';
                $sets = $ex['sets'] ?? 3;
                $reps = $ex['reps'] ?? 10;
                $rest = $ex['rest'] ?? '60 seconds';
                $difficulty = $ex['difficulty'] ?? 'Beginner';
                $targetMuscleGroup = $ex['targetMuscleGroup'] ?? 'General';
                $secondaryMuscles = $ex['secondaryMuscles'] ?? '';
                $instructions = $ex['instructions'] ?? $description;
                $equipment = $ex['equipment'] ?? 'Bodyweight';
                $notes = $ex['notes'] ?? '';
                
                // Check if exercise exists
                $existing = select('Exercise', 'Exercise_ID', ['Name' => $name]);
                if (empty($existing)) {
                    // Insert new exercise
                    $exerciseData = [
                        'Name' => $name,
                        'Description' => $description,
                        'Difficultly' => $difficulty,
                        'Target_Muscle_Group' => $targetMuscleGroup,
                        'Secondary_Muscles' => $secondaryMuscles,
                        'Instuctions' => $instructions,
                        'Equipment_Required' => $equipment,
                        'Video_url' => '',
                        'Created_at' => date('Y-m-d H:i:s'),
                        'Updated_at' => date('Y-m-d H:i:s')
                    ];
                    $exerciseId = insert('Exercise', $exerciseData);
                } else {
                    $exerciseId = $existing[0]['Exercise_ID'];
                }
                
                // Insert into WorkoutExercise
                $workoutExData = [
                    'Sequence_Order' => $sequence++,
                    'Day_Number' => $dayNumber,
                    'Sets' => $sets,
                    'Reps' => $reps,
                    'Rest_Time' => $rest,
                    'Notes' => $notes,
                    'Exercise_ID' => $exerciseId,
                    'Workout_ID' => $workoutId
                ];
                insert('WorkoutExercise', $workoutExData);
            }
        }
        echo "Workout plan saved to database for Ahmed.";
        
        // Display the generated plan
        $title = $program['title'] ?? '1-Week Muscle Building Plan';
        $description = $program['description'] ?? 'Beginner workout plan generated by AI';
        $goal = $program['goal'] ?? 'Build Muscle';
        $weeks = $program['weeks'] ?? 1;
        echo "<h2>$title</h2>";
        echo "<p>$description</p>";
        echo "<p>Goal: $goal</p>";
        echo "<p>Duration: $weeks weeks</p>";
        
        foreach ($days as $day => $exercises) {
            $dayName = ucfirst($day);
            echo "<h3>$dayName</h3>";
            echo "<ul>";
            foreach ($exercises as $ex) {
                $name = $ex['name'] ?? 'Unknown Exercise';
                $sets = $ex['sets'] ?? 3;
                $reps = $ex['reps'] ?? 10;
                $rest = $ex['rest'] ?? '60 seconds';
                echo "<li>" . htmlspecialchars($name) . ": $sets sets of $reps reps, rest $rest</li>";
            }
            echo "</ul>";
        }
    } else {
        echo "Failed to create workout program.";
    }
} else {
    echo $response; // Error message
}
echo '</div></body></html>';
?>
