<?php

?>

<link rel="stylesheet" href="../ChatBot Full/ChatBot.Css">
<script src="../ChatBot Full/ChatBot.js" defer></script>
<button id="chatbot-toggle-btn"><img src="../ChatBot Full/chat-bot_12134131.png" width="50" height="50" alt="buttonpng" /></button>
<div class="chatbot-popup" id="chatbot-popup">
  <div class="chat-header">
    <span>Chatbot | <a href="#" target="_blank"> Power Gym</a></span>
    <button id="close-btn">&times;</button>
  </div>
  <div class="chat-box" id="chat-box"></div>
  <div class="chat-input">
    <input type="text" id="user-input" placeholder="Type a message...">
    <button id="send-btn">Send</button>
  </div>
  <div class="copyright">
    <a href="#" target="_blank"> Made By Power Gym © 2025</a>
  </div>
</div>