<?php
require_once __DIR__ . '/../../../DB.php';
require_once __DIR__ . '/../../helpers/auth.php';
header('Content-Type: application/json');

require_role(['coach','admin']);

$raw = file_get_contents('php://input');
$data = json_decode($raw, true) ?: $_POST;

if (empty($data['member_id']) || empty($data['workout'])) {
    echo json_encode(['error' => 'member_id and workout data required']);
    exit;
}

$memberId = (int)$data['member_id'];
$coachId = current_user_id();
$workoutData = $data['workout'];

$program = $workoutData['program'] ?? [];
$days = $workoutData['days'] ?? [];

if (empty($program) || empty($days)) {
    echo json_encode(['error' => 'Invalid workout data structure']);
    exit;
}

// Start transaction for atomic operations
$conn->begin_transaction();

try {
    // Deactivate any existing active programs for this member
    $deactivateStmt = $conn->prepare("UPDATE workoutprogram SET Status = 'Inactive', Updated_at = NOW() WHERE Member_Id = ? AND Status = 'Active' AND Coach_ID = ?");
    $deactivateStmt->bind_param('ii', $memberId, $coachId);
    $deactivateStmt->execute();
    $deactivateStmt->close();
    
    // Hard delete any pending workout programs for this member
    // First, get all pending workout program IDs
    $getPendingStmt = $conn->prepare("SELECT Workout_ID FROM workoutprogram WHERE Member_Id = ? AND Status = 'Pending' AND Coach_ID = ?");
    $getPendingStmt->bind_param('ii', $memberId, $coachId);
    $getPendingStmt->execute();
    $pendingResult = $getPendingStmt->get_result();
    $pendingWorkoutIds = [];
    while ($row = $pendingResult->fetch_assoc()) {
        $pendingWorkoutIds[] = (int)$row['Workout_ID'];
    }
    $getPendingStmt->close();
    
    // Hard delete related workout exercises for pending programs
    if (!empty($pendingWorkoutIds)) {
        $placeholders = implode(',', array_fill(0, count($pendingWorkoutIds), '?'));
        $deleteExercisesStmt = $conn->prepare("DELETE FROM workoutexercise WHERE Workout_ID IN ($placeholders)");
        $types = str_repeat('i', count($pendingWorkoutIds));
        $deleteExercisesStmt->bind_param($types, ...$pendingWorkoutIds);
        $deleteExercisesStmt->execute();
        $deleteExercisesStmt->close();
        
        // Hard delete the pending workout programs
        $deletePendingStmt = $conn->prepare("DELETE FROM workoutprogram WHERE Workout_ID IN ($placeholders)");
        $deletePendingStmt->bind_param($types, ...$pendingWorkoutIds);
        $deletePendingStmt->execute();
        $deletePendingStmt->close();
    }
    
    // Commit transaction before creating new program
    $conn->commit();
} catch (Exception $e) {
    $conn->rollback();
    echo json_encode(['error' => 'Failed to clean up existing programs: ' . $e->getMessage()]);
    exit;
}

// Insert into WorkoutProgram
$now = date('Y-m-d H:i:s');
$weeks = isset($program['weeks']) ? (int)$program['weeks'] : 4;
$programData = [
    'Title' => $program['title'] ?? 'AI Generated Workout Plan',
    'Description' => $program['description'] ?? 'Workout plan generated by AI',
    'Goal' => $program['goal'] ?? 'General fitness',
    'Weeks_Duration' => $weeks,
    'Start_Date' => date('Y-m-d'),
    'End_Date' => date('Y-m-d', strtotime("+{$weeks} weeks")),
    'Status' => 'Active',
    'Created_at' => $now,
    'Updated_at' => $now,
    'Member_Id' => $memberId,
    'Coach_ID' => $coachId
];

$workoutId = insert('workoutprogram', $programData);

if (!$workoutId) {
    echo json_encode(['error' => 'Failed to create workout program']);
    exit;
}

// Insert exercises and workout exercises
$sequence = 1;
$exercisesCreated = 0;
$errors = [];

foreach ($days as $day => $exercises) {
    if (empty($exercises) || !is_array($exercises)) continue;
    
    $dayNumber = (int)str_replace('day', '', $day);
    
    foreach ($exercises as $ex) {
        if (empty($ex['name'])) continue;
        
        $name = $ex['name'];
        $description = $ex['description'] ?? '';
        $sets = isset($ex['sets']) ? (int)$ex['sets'] : 3;
        $reps = isset($ex['reps']) ? (int)$ex['reps'] : 10;
        $rest = $ex['rest'] ?? '60 seconds';
        $difficulty = $ex['difficulty'] ?? 'Beginner';
        $targetMuscleGroup = $ex['targetMuscleGroup'] ?? 'General';
        $secondaryMuscles = $ex['secondaryMuscles'] ?? '';
        $instructions = $ex['instructions'] ?? $description;
        $equipment = $ex['equipment'] ?? 'Bodyweight';
        $notes = $ex['notes'] ?? '';
        
        // Check if exercise exists
        $existing = select('exercise', 'Exercise_ID', ['Name' => $name]);
        $exerciseId = null;
        
        if (!empty($existing)) {
            $exerciseId = $existing[0]['Exercise_ID'];
        } else {
            // Insert new exercise
            $exerciseData = [
                'Name' => $name,
                'Description' => $description,
                'Difficultly' => $difficulty,
                'Target_Muscle_Group' => $targetMuscleGroup,
                'Secondary_Muscles' => $secondaryMuscles,
                'Instuctions' => $instructions,
                'Equipment_Required' => $equipment,
                'Video_url' => '',
                'Created_at' => $now,
                'Updated_at' => $now
            ];
            $exerciseId = insert('exercise', $exerciseData);
            
            if (!$exerciseId) {
                $errors[] = "Failed to create exercise: {$name}";
                continue;
            }
        }
        
        // Insert into WorkoutExercise
        $workoutExData = [
            'Sequence_Order' => $sequence++,
            'Day_Number' => $dayNumber,
            'Sets' => $sets,
            'Reps' => $reps,
            'Rest_Time' => $rest,
            'Notes' => $notes,
            'Exercise_ID' => $exerciseId,
            'Workout_ID' => $workoutId
        ];
        
        $weId = insert('workoutexercise', $workoutExData);
        if ($weId) {
            $exercisesCreated++;
        } else {
            $errors[] = "Failed to add exercise to workout: {$name}";
        }
    }
}

echo json_encode([
    'success' => true,
    'workout_id' => $workoutId,
    'exercises_created' => $exercisesCreated,
    'errors' => $errors
]);
?>

